fix(profiling) wrong integration casing
getsentry/sentry-docs pull request #10382
Opened 2024-06-12 20:41 UTC by JonasBa

The diffs are sad, but the casing used before was `Sentry.BrowserProfilingIntegration` whereas it should be `Sentry.browserProfilingIntegration`

2024-06-12 20:46 UTC, Zylphrex approved these changes

2024-06-12 21:55 UTC, vivianyentran approved these changes

2024-06-13 11:56 UTC, stephanie-anderson requested changes
Hey @JonasBa - the contents in `public/` must not be changed (and will be overwritten anyways). Please update the corresponding .mdx files in `docs/`, `includes/` or `platform-includes/`

2024-06-13 12:05 UTC, stephanie-anderson commented
> Hey @JonasBa - the contents in `public/` must not be changed (and will be overwritten anyways). Please update the corresponding .mdx files in `docs/`, `includes/` or `platform-includes/`

Sorry, found the [reason](https://github.com/getsentry/sentry-docs/blob/master/public/_platforms/_README.md) for this. Will follow up with the Telemetry Experience team if this is still needed.

2024-06-13 13:50 UTC, JonasBa commented
@stephanie-anderson we still need this because the docs on the sentry dashboard are still using this. 

I found no other reference to these files in any mdx docs, so I assume they are the correct source and need to update them, else the in-app onboarding is broken.

2024-06-13 16:31 UTC, stephanie-anderson approved these changes

2024-06-13 16:37 UTC, merged