self-hosted: minimum system requirements
getsentry/sentry-docs pull request #11135
Opened 2024-08-23 18:48 UTC by joshuarli

current stuff is outdated, felt it would be best to just link to our readme since that's more updated in tandem with `install/_min-requirements.sh    `

2024-08-23 23:49 UTC, aldy505 requested changes
Hey don't do this. We shouldnt be referring to the SH's README anymore. What we should do is the opposite: from the README, we refer to the docs site. So there'll be more centralized docs about SH.

2024-08-26 20:39 UTC, vivianyentran approved these changes

2024-08-26 21:37 UTC, hubertdeng123 commented
@aldy505 The docs website is linked in self-hosted README already. To be honest, I would agree and say that self-hosted README should be mostly removed besides basic installation instructions in favor of the docs website given that it's mostly duplicate information. Any thoughts here @BYK ?

2024-08-26 21:58 UTC, BYK commented
![kill-it-with-fire-kill](https://github.com/user-attachments/assets/88344c16-ff41-4ba7-9423-c43dc79e7260)

2024-08-26 22:01 UTC, aldy505 commented
> @aldy505 The docs website is linked in self-hosted README already. To be honest, I would agree and say that self-hosted README should be mostly removed besides basic installation instructions in favor of the docs website given that it's mostly duplicate information. Any thoughts here @BYK ?

@hubertdeng123 I prefer an even drastic approach, the readme should only contains "version", a small description about what SH is, and "for everything about this, see the website". 😆

2024-08-29 19:19 UTC, joshuarli commented
Sounds good, I'll follow up with moving the self-hosted README over here.

2024-08-29 19:26 UTC, merged

2024-08-30 09:15 UTC, aldy505 commented
> Sounds good, I'll follow up with moving the self-hosted README over here.

@joshuarli already did here https://github.com/getsentry/sentry-docs/pull/10883