feat(profiling): add sample format V2 documentation
getsentry/sentry-docs pull request #11150
Opened 2024-08-27 09:44 UTC by viglia

## DESCRIBE YOUR PR
Add documentation for profile sample format version 2.

## IS YOUR CHANGE URGENT?  

Help us prioritize incoming PRs by letting us know when the change needs to go live.
- [ ] Urgent deadline (GA date, etc.): 
- [ ] Other deadline: 
- [ ] None: Not urgent, can wait up to 1 week+

## SLA

- Teamwork makes the dream work, so please add a reviewer to your PRs.
- Please give the docs team up to 1 week to review your PR unless you've added an urgent due date to it.
Thanks in advance for your help!

## PRE-MERGE CHECKLIST

*Make sure you've checked the following before merging your changes:*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs (subject matter experts)
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## LEGAL BOILERPLATE

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

## EXTRA RESOURCES

- [Sentry Docs contributor guide](https://docs.sentry.io/contributing/)

2024-08-29 15:10 UTC, phacops requested changes

2024-08-29 15:10 UTC, phacops commented on develop-docs/sdk/telemetry/profiles/sample-format-v2.mdx
> +- `elapsed_since_start_ns`: number of nanoseconds since the start of the profile
`V2` expects a unix timestamp with microsecond precision (like for samples), in a field called `timestamp`.

https://github.com/getsentry/relay/blob/master/relay-profiling/src/measurements.rs#L25

2024-08-29 15:10 UTC, phacops commented on develop-docs/sdk/telemetry/profiles/sample-format-v2.mdx
> +      "elapsed_since_start_ns: "1234567890",
This field should be `timestamp`.

2024-08-29 15:10 UTC, phacops commented on develop-docs/sdk/telemetry/profiles/sample-format-v2.mdx
> +- `timestamp`: *64-bit floating point, required.* Contains the Unix timestamp
We'd like microsecond precisions instead of millisecond. In general, the more precise you are the better.

2024-08-29 22:39 UTC, vivianyentran approved these changes
Added some suggestions

2024-08-29 22:39 UTC, vivianyentran commented on develop-docs/sdk/telemetry/profiles/sample-format-v1.mdx
> +: *Object, required on native platforms.* This carry the same payload as <Link
```suggestion
: *Object, required on native platforms.* This carries the same payload as the <Link
```

2024-08-29 22:39 UTC, vivianyentran commented on develop-docs/sdk/telemetry/profiles/sample-format-v1.mdx
> +have it for native platforms in order to symbolicate, otherwise you can omit it.
```suggestion
have it for native platforms in order to symbolicate. For non-native platforms, you can omit this.
```

2024-08-29 22:39 UTC, vivianyentran commented on develop-docs/sdk/telemetry/profiles/sample-format-v1.mdx
> +: *Object, required.* This contains a few fields to describe the device the
```suggestion
: *Object, required.* This contains several fields that describe the device the
```

2024-08-29 22:39 UTC, vivianyentran commented on develop-docs/sdk/telemetry/profiles/sample-format-v1.mdx
> +- `manufacturer`: *String, optional.* Contains the manufacturer of the device. Usually only set for a mobile platforms.
```suggestion
- `manufacturer`: *String, optional.* Contains the manufacturer of the device. Usually only set for mobile platforms.
```

2024-08-29 22:39 UTC, vivianyentran commented on develop-docs/sdk/telemetry/profiles/sample-format-v1.mdx
> +- `model`: *String, optional.* Contains the model of the device. Usually only set for a mobile platforms.
```suggestion
- `model`: *String, optional.* Contains the model of the device. Usually only set for mobile platforms.
```

2024-08-29 22:39 UTC, vivianyentran commented on develop-docs/sdk/telemetry/profiles/sample-format-v1.mdx
> +`staging`. The default value should be `production`.
```suggestion
`staging`. The default value is `production`.
```

2024-08-29 22:39 UTC, vivianyentran commented on develop-docs/sdk/telemetry/profiles/sample-format-v1.mdx
> +is exactly 32 characters. Dashes are not allowed. Has to be lowercase.
```suggestion
: *String, required.* Hexadecimal string representing a uuid4 value. The length
must be exactly 32 characters. Dashes and uppercase letters are not allowed.
```

2024-09-03 15:12 UTC, phacops approved these changes

2024-09-03 15:13 UTC, merged