docs(nextjs): Add troubleshooting for OOM
getsentry/sentry-docs pull request #12093
Opened 2024-12-11 13:34 UTC by chargome

ref https://github.com/getsentry/sentry-javascript/issues/10468

Adds a troubleshooting section to nextjs for the OOM issue while building.

2024-12-11 13:40 UTC, lforst commented on docs/platforms/javascript/common/troubleshooting/index.mdx
> +    - Increase Node.js memory limit: You can try increasing the memory limit for Node.js during the build process. Add this to your build command: `NODE_OPTIONS="--max-old-space-size=4096" next build
```suggestion
    - Increase Node.js memory limit: You can try increasing the memory limit for Node.js during the build process. Add this to your build command: `NODE_OPTIONS="--max-old-space-size=8192" next build`. This flag will increase the memory available to the node process to 8 GB. We have found that Next.js consumes around 4 GB in most cases. Decrease the size depending on your memory availability.
```

2024-12-12 00:21 UTC, coolguyzone commented on docs/platforms/javascript/common/troubleshooting/index.mdx
> +<Alert level="warning">
Looks like this note is getting repeated 👯
<img width="734" alt="Screenshot 2024-12-11 at 4 21 00 PM" src="https://github.com/user-attachments/assets/a4921d66-8114-4023-8f90-2cbeb59a8241" />

2024-12-12 00:24 UTC, coolguyzone commented on docs/platforms/javascript/common/troubleshooting/index.mdx
> +    The problem is related to memory consumption during the build process, especially when generating source maps. Here are some potential solutions and workarounds:
```suggestion
    The problem here is related to memory consumption during the build process, especially when generating source maps. Here are some potential solutions and workarounds:
```

2024-12-12 00:24 UTC, coolguyzone requested changes
We need to get rid of the duplicate note, then this will be good to go!

2024-12-12 09:57 UTC, merged