Feat/node lambda docs
getsentry/sentry-docs pull request #2204
Opened 2020-09-07 20:28 UTC by ajjindal

Latest Node AWS integration docs update

2020-09-09 10:47 UTC, kamilogorek requested changes

2020-09-09 10:47 UTC, kamilogorek commented on src/platforms/node/guides/aws-lambda/index.mdx
> +_(New in version 5.22.4 - Lambda integration is in Beta)_
It'll be `5.23.0`

2020-09-09 10:47 UTC, kamilogorek commented on src/platforms/node/guides/aws-lambda/index.mdx
> +    "___PUBLIC_DSN___",
```suggestion
  dsn: "___PUBLIC_DSN___"
```

2020-09-09 10:47 UTC, kamilogorek commented on src/platforms/node/guides/aws-lambda/index.mdx
> +You can use the AWS Lambda integration for the Node SDK like this:
I'd remove the `SDK` part from the `Node SDK`

2020-09-09 10:47 UTC, kamilogorek commented on src/platforms/node/guides/aws-lambda/index.mdx
> +const myAsyncHandler = async (event, context, callback) => {
```suggestion
const myAsyncHandler = async (event, context) => {
```

`async` functions are mutually exclusive with `callback`. It's either async or sync with callback.

2020-09-09 10:47 UTC, kamilogorek commented on src/platforms/node/guides/aws-lambda/index.mdx
> +Sentry reports timeout warning when the function is within 500ms of it's execution time. You can turn off timeout warnings by setting `captureTimeoutWarning` to `false` during initiatlization. To cha
This is now how options are set for handlers.

```js
Sentry.AWSLambda.wrapHandler(yourHandler, {
  captureTimeoutWarning: false
});
```

So both, description and code examples are incorrect.

2020-09-09 10:47 UTC, kamilogorek commented on src/platforms/node/guides/aws-lambda/index.mdx
> +The timeout warning is sent only if the "timeout" in the Lambda Function configuration is set to a value greater than one second.
There's nothing stopping you from setting timeout to `1s` and still capture the warning if limit is small enough.

2020-09-09 10:47 UTC, kamilogorek commented on src/platforms/node/guides/aws-lambda/index.mdx
> +- Sentry holds the thread for upto 2 seconds to report errors. You can change flush time limit by defining a `flushTimeout` value during initiatlization
in the handler options*

2020-09-09 10:47 UTC, kamilogorek commented on src/wizard/node/awslambda.md
> +You can use the AWS Lambda integration for the Node SDK like this:
All the comments apply to this file as well, so I won't double-post them.

2020-10-13 08:45 UTC, HazAT commented
Outdated

2020-10-13 08:45 UTC, closed without merging