feat: Parse backticks as html code elements
getsentry/sentry-docs pull request #2368
Opened 2020-09-25 20:05 UTC by NisanthanNanthakumar

## Objective
All code formatted strings are formatted properly.

Parsing function should be O(n). **Can this be improved?**

## UI
*BEFORE*
<img width="1440" alt="Screen Shot 2020-09-25 at 1 01 23 PM" src="https://user-images.githubusercontent.com/10491193/94311057-78981500-ff2f-11ea-9423-84bba613bf1b.png">

*AFTER*
<img width="1440" alt="Screen Shot 2020-09-25 at 1 03 05 PM" src="https://user-images.githubusercontent.com/10491193/94311076-7fbf2300-ff2f-11ea-9373-c2a457aee3fb.png">

2020-09-25 20:22 UTC, mgaeta requested changes
`parseBackticks` needs tests.

2020-09-25 20:22 UTC, mgaeta commented on src/templates/apiPage.tsx
> +    for (i <= j; i++; ) {
```
for (; i <= j; i++) {
```

2020-09-25 20:23 UTC, mgaeta commented
This will fail with:
```
`foo` `foo`
```

2020-09-25 20:31 UTC, mgaeta commented
```
const parseBackticks = (str) => {
  let i = 0;
  return str.split("").map((c) => {
    return c === "`" ? (i++ % 2 ? "</code>": "<code>") : c;
  }).join("");
};
```

2020-09-25 20:38 UTC, NisanthanNanthakumar commented
> const parseBackticks = (str) => {
>   let i = 0;
>   return str.split("").map((c) => {
>     return c === "`" ? (i++ % 2 ? "</code>": "<code>") : c;
>   }).join("");
> };

lol I didn't realize it would break for consecutive, this a good one!!

2020-09-25 20:38 UTC, manuzope commented
Hmmm, I don't know if docs even have tests 🤔

2020-09-25 20:49 UTC, NisanthanNanthakumar commented
> Hmmm, I don't know if docs even have tests 🤔

Not alot, but the structure is there

2020-09-25 21:02 UTC, mgaeta approved these changes
👍

2020-09-28 19:00 UTC, mgaeta approved these changes
Ok this looks good but there is one more edge case: `` ` `` (a code block containing a single backtick). I don't think we'll actually see that in the docs but I think you should add a comment describing why we squash backticks and why this case isn't covered.

2020-09-28 20:52 UTC, merged