Java DataSource instrumentation.
getsentry/sentry-docs pull request #3353
Opened 2021-04-05 15:22 UTC by maciejwalkowiak

Fixes #3337

2021-04-05 15:46 UTC, maciejwalkowiak commented
Not sure if that's the best place to put these docs - but considering they can be used independently from Spring - and with Spring they can be used either with manual DataSource bean creation or through the 3rd party starter - I think it makes sense to keep it on the separate page.

2021-04-06 07:18 UTC, marandaneto commented on src/platforms/java/common/performance/datasource.mdx
> +DataSource dataSource = // original datasource
should we add the import for this?

2021-04-06 07:19 UTC, marandaneto commented on src/platforms/java/common/performance/datasource.mdx
> +
lets add a note similar to OkHttp this is a preview https://docs.sentry.io/platforms/android/configuration/integrations/okhttp/

2021-04-06 07:21 UTC, marandaneto commented
let's keep it as a Draft till cutting a release

2021-04-06 13:44 UTC, imatwawana approved these changes
Made some minor wording edits

2021-04-06 13:44 UTC, imatwawana commented on src/platforms/java/common/performance/datasource.mdx
> +To start using *Sentry P6Spy* integration, include following dependency in your project:
```suggestion
To start using the *Sentry P6Spy* integration, include the following dependency in your project:
```

2021-04-06 13:44 UTC, imatwawana commented on src/platforms/java/common/performance/datasource.mdx
> +](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator). *Sentry Spring Boot Starter* provides auto-configuration classes creating `SentryJdbcEventListener` and `SentryQueryExecutionLis
```suggestion
Spring Boot, out of the box, does not provide datasource proxying capabilities. We recommend using either the *Sentry P6Spy* or *Sentry DataSource Proxy* integration with a third party library [Spring Boot DataSource Decorator](https://github.com/gavlyukovskiy/spring-boot-data-source-decorator). *Sentry Spring Boot Starter* provides auto-configuration classes, creating `SentryJdbcEventListener` and `SentryQueryExecutionListener` beans when respective integrations are on the classpath.
```

2021-04-09 10:30 UTC, marandaneto approved these changes
LGTM

2021-04-09 23:58 UTC, PeloWriter approved these changes
LGTM

2021-04-12 16:56 UTC, bruno-garcia requested changes
We're having problems publishing the artifacts to central because of this dependency.
And given that the primary requester of this feature is currently not going to use it, we're considering not releasing the new packages. For that reason lets keep this PR in draft state for now please.

2021-04-28 08:02 UTC, marandaneto commented
as we deferred publishing the packages, closing it for now

2021-04-28 08:02 UTC, closed without merging