Provided clarity around LinkedErrors
getsentry/sentry-docs pull request #3446
Opened 2021-04-22 06:36 UTC by sentryadam0000345

Added a code example for LinkedErrors as well as a screenshot on how it should look like.

2021-04-22 15:51 UTC, PeloWriter commented on src/platforms/javascript/common/configuration/integrations/default.mdx
> +<img width="928" alt="Screen Shot 2021-04-21 at 11 34 50 PM" src="https://user-images.githubusercontent.com/65051899/115667031-2d45b980-a2fa-11eb-8689-b6d6011a67f6.png">
thanks for adding this content. Looks like the image doesn't use our guidelines, which I'll forward to you on Slack. The basics (for future reference):
![text_for_image_if_not_displayed](image_name.png)

2021-04-22 18:35 UTC, rhcarvalho reviewed
@kamilogorek could you please sanity-check the example here matches how it works?

2021-04-22 18:35 UTC, rhcarvalho commented on src/platforms/javascript/common/configuration/integrations/default.mdx
> +
```suggestion

```

Too many empty line here.

2021-04-23 09:11 UTC, kamilogorek requested changes

2021-04-23 09:11 UTC, kamilogorek commented on src/platforms/javascript/common/configuration/integrations/default.mdx
> +```
```suggestion
```javascript
document.querySelector('#teststuff').addEventListener('click', async (event) => {
  const movie = event.target.dataset.title;
  try {
    const reviews = await fetchMovieReviews(movie);
    renderMovieReviews(reviews);
  } catch (e) {
    const fetchError = new Error(`Failed to fetch reviews for: ${movie}`);
    fetchError.cause = e;
    Sentry.captureException(fetchError);
    renderMovieReviewsError(fetchError);
  }
});
```
```

2021-04-23 09:11 UTC, kamilogorek commented on src/platforms/javascript/common/configuration/integrations/default.mdx
> +```
This will be more real-world friendly example.

2021-04-23 10:26 UTC, rhcarvalho commented on src/platforms/javascript/common/configuration/integrations/default.mdx
> +});
```suggestion
});

```

2021-04-23 10:30 UTC, rhcarvalho approved these changes
Thanks @sentryadam0000345. Used Kamil's version for the added "real worldness".

2021-04-23 10:33 UTC, merged