add type restriction for contexts
getsentry/sentry-docs pull request #3557
Opened 2021-05-10 17:04 UTC by imatwawana

Adds `type` key restriction for contexts to all SDK docs

2021-05-10 17:41 UTC, rhcarvalho requested changes
I feel like I somewhat understand the intent here, but in fact `type` is NOT forbidden, it just carries a special meaning:

![image](https://user-images.githubusercontent.com/88819/117701444-89984c80-b1c7-11eb-9bac-95d638c08c94.png)
(https://develop.sentry.dev/sdk/event-payloads/contexts/)

2021-05-11 13:51 UTC, iker-barriocanal commented on src/platforms/common/enriching-events/context.mdx
> +Learn more about conventions for common contexts in the [contexts interface developer documentation](https://develop.sentry.dev/sdk/event-payloads/contexts/).
```suggestion
Although there are no restrictions for naming contexts or their fields, keep in mind the key `type` has a default value set in each context. Learn more about the default values and conventions for common contexts in the [contexts interface developer documentation](https://develop.sentry.dev/sdk/event-payloads/contexts/).
```

2021-05-11 14:08 UTC, imatwawana commented on src/platforms/common/enriching-events/context.mdx
> +Learn more about conventions for common contexts in the [contexts interface developer documentation](https://develop.sentry.dev/sdk/event-payloads/contexts/).
@rhcarvalho Does what I wrote or what @iker-barriocanal  suggested work?

2021-05-11 20:45 UTC, rhcarvalho commented
Hmm this seemingly trivial change got a little confusing :)

@imatwawana could you please document in the PR description what problem we're trying to solve here?

Is the main concern that someone set `type` and it didn't work? Is there an existing issue on GitHub?

To avoid bikeshedding this too much, let's go with Katie's suggestion https://github.com/getsentry/sentry-docs/pull/3557#discussion_r630247280, as that's good enough.

2021-05-11 21:06 UTC, imatwawana commented
@rhcarvalho I've updated the description of this PR with the description from the linked issue and committed the suggestion from @lobsterkatie.

2021-05-14 16:51 UTC, PeloWriter commented
Looks like we've settled on a fix for this issue - any reason to hold on merging @rhcarvalho ?

2021-05-15 13:48 UTC, rhcarvalho approved these changes

2021-05-15 13:49 UTC, merged

2021-05-15 13:50 UTC, rhcarvalho commented
Thanks @imatwawana!