ref: Node DB auto-instrumentation docs
getsentry/sentry-docs pull request #3563
Opened 2021-05-11 07:41 UTC by kamilogorek

Implementation: https://github.com/getsentry/sentry-javascript/pull/3483

2021-05-11 07:44 UTC, HazAT approved these changes
🥇  Let's merge this once we released the SDK

2021-05-11 13:30 UTC, lobsterkatie requested changes
Can we also document a) how to configure an auto-enabled integration, and b) what options there are to configure for each?

2021-05-11 13:30 UTC, lobsterkatie commented on src/platforms/node/common/performance/database.mdx
> +Node.js has a few integrations that support tracking database queries as Spans. Starting version `6.4.0`, when you are using one of the supported database drivers or ORMs, the integration is installe
```suggestion
Node.js has a few integrations that support tracking database queries as spans. Starting version `6.4.0`, `@sentry/tracing` will auto-detect supported database drivers or ORMs being used in your project, and automatically enable the relevant integrations with default options - no additional code necessary.
```

2021-05-11 13:30 UTC, lobsterkatie commented on src/platforms/node/common/performance/database.mdx
> +To remove an integration, please refer to our [integrations](/platforms/node/configuration/integrations/#removing-an-integration) docs.
```suggestion
To learn how to remove an automatically-enabled integration, please refer to our [integrations](/platforms/node/configuration/integrations/#removing-an-integration) docs.
```

I actually think we might to well to have an example here, even with the link.

2021-05-11 21:56 UTC, PeloWriter approved these changes
Minor edits to smooth.

2021-05-11 21:56 UTC, PeloWriter commented on src/platforms/node/common/performance/database.mdx
> +Node.js has a few integrations that support tracking database queries as spans. Starting version `6.4.0`, `@sentry/tracing` will auto-detect supported database drivers or ORMs being used in your proj
```suggestion
Node.js integrations support tracking database queries as spans. Starting in version `6.4.0`, `@sentry/tracing` will auto-detect supported database drivers or ORMs being used in your project, and automatically enable the relevant integrations with default options - without needing additional code.
```

2021-05-11 21:56 UTC, PeloWriter commented on src/platforms/node/common/performance/database.mdx
> +Supported packages and their integration name are, respectively: `pg` (Postgres), `mongodb` (Mongo), `mongoose` (Mongo) and `mysql` (Mysql).
```suggestion
Supported packages and their integration name: 
- `pg` (Postgres)
- `mongodb` (Mongo)
- `mongoose` (Mongo)
- `mysql` (MySQL)
```

2021-05-11 21:56 UTC, PeloWriter commented on src/platforms/node/common/performance/database.mdx
> +### Adding integrations manually
```suggestion
### Manually Adding Integrations
```

2021-05-12 07:51 UTC, ahmedetefy approved these changes

2021-05-18 21:38 UTC, merged