Add Next.js SDK's performance monitoring docs
getsentry/sentry-docs pull request #3653
Opened 2021-05-28 09:29 UTC by iker-barriocanal

Docs for the new performance monitoring of the Next.js SDK.

2021-05-28 14:45 UTC, iker-barriocanal commented
@rahulchhabria

2021-05-31 12:17 UTC, AbhiPrasad reviewed
What do you think about switching from `frontend` -> `client-side` and `backend` -> `server-side`? I think that better matches to how nextjs refers to those concepts, but I'm not sure it is as clear as just saying frontend, backend.

2021-05-31 13:22 UTC, iker-barriocanal commented
> What do you think about switching from `frontend` -> `client-side` and `backend` -> `server-side`? I think that better matches to how nextjs refers to those concepts, but I'm not sure it is as clear as just saying frontend, backend.

Yes @AbhiPrasad, in fact, that's the language we've been using in the SDK. Updated.

2021-05-31 13:30 UTC, AbhiPrasad requested changes
We need some indication that performance monitoring is only available for the SDK v6.5.0, otherwise people will def get confused. I left a comment on for one place where we can add it, but there might be more places.

2021-05-31 13:30 UTC, AbhiPrasad commented on src/includes/getting-started-primer/javascript.nextjs.mdx
> +- Automatic [Performance Monitoring](/product/performance/) for both the client and server
Can we put something like `**new in 6.5.0**`?

2021-06-01 10:18 UTC, HazAT requested changes
We should also add it to the wizard `tracesSampleRate`

2021-06-01 10:41 UTC, HazAT approved these changes
Sorry, it's already there 😓

2021-06-01 10:51 UTC, merged