Fix koa tracing code snippet to trace database queries
getsentry/sentry-docs pull request #3862
Opened 2021-07-12 14:11 UTC by fabioDMFerreira

The previous implementation didn't trace database queries performance. The current implementation gives the chance of finishing spans before closing the transaction.

2021-07-12 17:53 UTC, PeloWriter commented
@vladanpaunovic - can the Web platform team please review?

2021-07-13 11:07 UTC, seromenho approved these changes
💪

2021-07-19 08:54 UTC, kamilogorek requested changes
Just minor style tweaks. Otherwise 👍

2021-07-19 08:54 UTC, kamilogorek commented on src/platforms/node/guides/koa/index.mdx
> +  });
```suggestion
  Sentry.getCurrentHub().configureScope(scope => {
    scope.setSpan(transaction);
  });
```

2021-07-19 08:54 UTC, kamilogorek commented on src/platforms/node/guides/koa/index.mdx
> +  await next();
```suggestion
  ctx.res.on("finish", () => {
    // Push `transaction.finish` to the next event loop so open spans have a chance to finish before the transaction closes
    setImmediate(() => {
      // if using koa router, a nicer way to capture transaction using the matched route
      if (ctx._matchedRoute) {
        const mountPath = ctx.mountPath || "";
        transaction.setName(`${reqMethod} ${mountPath}${ctx._matchedRoute}`);
      }
      transaction.setHttpStatus(ctx.status);
      transaction.finish();
    });
  });

  await next();
```

2021-07-19 09:50 UTC, kamilogorek approved these changes
Thanks

2021-07-19 12:12 UTC, merged