Fix typo in example code
getsentry/sentry-docs pull request #4464
Opened 2021-12-03 16:44 UTC by set0gut1

2021-12-06 10:04 UTC, untitaker approved these changes

2021-12-06 10:05 UTC, untitaker requested changes
actually can you change the comment above to match the rule

Ignoring all sourcefiles isn't a very realistic example. I think `.gen.c` is supposed to be an example where generated C source code is excluded from grouping.

2021-12-07 06:30 UTC, set0gut1 commented
@untitaker Thanks for the review. I have fixed it.

2021-12-07 06:31 UTC, set0gut1 commented
@untitaker Thank you for review. I have fixed it.

2021-12-07 16:06 UTC, untitaker approved these changes

2021-12-07 16:06 UTC, merged