feat(issue-owners): Add to Code Owners and eval flow
getsentry/sentry-docs pull request #4560
Opened 2022-01-07 00:00 UTC by NisanthanNanthakumar

## Objective:
Explains the relationships between Ownership Rules, Code Owners and Code Mappings. I also added a section on the Evaluation Flow with an example and a section on how to setup Code Mappings, a prereq for Code Owners.

![localhost_3000_product_issues_issue-owners_ (1)](https://user-images.githubusercontent.com/10491193/148469137-5ed17a93-4eb1-45ee-8491-b2ba22b4bd7a.png)

2022-01-07 00:09 UTC, AniketDas-Tekky reviewed
LGTM

2022-01-07 00:09 UTC, AniketDas-Tekky commented on src/docs/product/issues/issue-owners/index.mdx
> +Sentry offers multiple ways to define the "ownership" of an issue. With ownership defined, we can automatically assign issues and send alerts to the owner. Sentry defines ownership with Code Owners a
Can we link to the Codeowners documentation on github?

2022-01-10 17:05 UTC, imatwawana requested changes
Overall, a really great addition! I've made several style fixes mostly around when and when not to capitalize things. If we're talking about the general concept of something, no caps (e.g., sometimes we're just talking an issue owner as a person), and if something isn't a high-level feature, or we're not referencing it directly in the UI, then also no caps (e.g., ownership rules, code owners). 

Also, you should make updates to these three files that reference ownership rules:
https://docs.sentry.io/product/sentry-basics/enrich-data/#issue-ownership
https://docs.sentry.io/product/issues/states-triage/#assign
https://docs.sentry.io/product/alerts/best-practices/#routing

2022-01-11 19:34 UTC, NisanthanNanthakumar commented on src/docs/product/issues/issue-owners/index.mdx
> +Sentry offers multiple ways to define the "ownership" of an issue. With ownership defined, we can automatically assign issues and send alerts to the owner. Sentry defines ownership with Code Owners a
@imatwawana the features are called Code Owners and Ownership Rules. I don't think it makes sense to have them lowercase.

2022-01-11 20:17 UTC, imatwawana commented on src/docs/product/issues/issue-owners/index.mdx
> +Sentry offers multiple ways to define the "ownership" of an issue. With ownership defined, we can automatically assign issues and send alerts to the owner. Sentry defines ownership with Code Owners a
We have _a lot_ of features so capitalizing all of them becomes cumbersome and when everything is capitalized, the importance of capitalization becomes diluted. Also, the capitalization across docs tends to be inconsistent, so I'm trying to impose a bit more structure in general around when we use it. As a style rule, we capitalize at the page level (so in this case Issue Owners page), but not features that are within a page unless we're doing a direct reference to them in the UI (in which case they'd be in quotation marks, e.g., the "Ownership Rules" section).

2022-02-18 21:27 UTC, imatwawana commented on src/docs/product/issues/issue-owners/index.mdx
> +Sentry offers multiple ways to define the "ownership" of an issue. With ownership defined, we can automatically assign issues and send alerts to the owner. Sentry defines ownership with _code owners_
Fixing a couple grammar issue here that arise with _code owners_ being plural. 

```suggestion
Sentry offers multiple ways to define the "ownership" of an issue. With ownership defined, we can automatically assign issues and send alerts to the owner. Sentry defines ownership with _code owners_ and _ownership rules_. Code owners functionality lets you import your GitHub or GitLab CODEOWNERS file, and then we assign issues according to those file paths. Ownership rules allow you to override the assignments based on code owners and provide advanced matcher types (for example, urls and tags). These rules can also match on the file paths of files in the stack trace, URL of the request, or event tags.
```

2022-02-28 20:06 UTC, imatwawana approved these changes

2022-02-28 20:09 UTC, imatwawana commented on src/docs/product/issues/issue-owners/index.mdx
> +Sentry offers multiple ways to define the "ownership" of an issue. With ownership defined, we can automatically assign issues and send alerts to the owner. Sentry defines ownership with _code owners_
```suggestion
Sentry offers multiple ways to define the "ownership" of an issue. With ownership defined, we can automatically assign issues and send alerts to the owner. Sentry defines ownership with _code owners_ and _ownership rules_. Code owners functionality lets you import your [GitHub or GitLab CODEOWNERS file](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners), and then we assign issues according to those file paths. Ownership rules allow you to override the assignments based on code owners and provide advanced matcher types (for example, urls and tags). These rules can also match on the file paths of files in the stack trace, URL of the request, or event tags.
```

2022-02-28 20:24 UTC, imatwawana commented on src/docs/product/issues/issue-owners/index.mdx
> +Sentry offers multiple ways to define the "ownership" of an issue. With ownership defined, we can automatically assign issues and send alerts to the owner. Sentry defines ownership with _code owners_
```suggestion
Sentry offers multiple ways to define the "ownership" of an issue. With ownership defined, we can automatically assign issues and send alerts to the owner. Sentry defines ownership with _code owners_ and _ownership rules_. Code owners functionality lets you import your [GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) or [GitLab](https://docs.gitlab.com/ee/user/project/code_owners.html) CODEOWNERS file, and then we assign issues according to those file paths. Ownership rules allow you to override the assignments based on code owners and provide advanced matcher types (for example, urls and tags). These rules can also match on the file paths of files in the stack trace, URL of the request, or event tags.
```

2022-02-28 21:03 UTC, imatwawana commented on src/docs/product/alerts/best-practices.mdx
> +- **Issue owners**: Use [ownership rules and code owners](/product/issues/issue-owners/) to let Sentry automatically send alerts to the right people, as well as to ease configuration burden. You can
```suggestion
- **Issue owners**: Use [ownership rules and code owners](/product/issues/issue-owners/) to let Sentry automatically send alerts to the right people, as well as to ease configuration burden. You can configure ownership in **[Project] > Settings > Issue Owners**. In the case of ownership rules, when there are no matching owners, the alert goes to all project members by default. If this is too broad, and you'd like a specific owner to be the fallback, end your ownership rules with a rule like `*:<owner>`.
```

2022-02-28 21:06 UTC, imatwawana commented on src/docs/product/sentry-basics/enrich-data/index.mdx
> +You'll be able to reduce noise by pinpointing notifications to the right people and automatically assigning new issues to their proper owners. You can configure ownership rules in **[Project] > Setti
```suggestion
You'll be able to reduce noise by pinpointing notifications to the right people and automatically assigning new issues to their proper owners. You can configure issue ownership in **[Project] > Settings > Issue Owners**. Learn more in [Issue Ownership](/product/error-monitoring/issue-owners/).
```

2022-02-28 22:39 UTC, NisanthanNanthakumar commented on src/docs/product/issues/states-triage/index.mdx
> +Assign issues to teams or individuals to route them to the right people and help you and your team see only relevant issues. Typically, assigning an issue to a team indicates that the team owns the i
```suggestion
Assign issues to teams or individuals to route them to the right people and help you and your team see only relevant issues. Typically, assigning an issue to a team indicates that the team owns the issue and that they're responsible for triaging it further. You can assign issues manually or automatically using [ownership rules and code owners](/product/issues/issue-owners/). On the issue list, you might also see a list of suggested assignees including the owners of suspect commits.
```

2022-02-28 23:41 UTC, merged