ref(rn): Remove expo troubleshooting and reword the expo package info
getsentry/sentry-docs pull request #5979
Opened 2022-12-19 13:19 UTC by krystofwoldrich

Remove the Expo troubleshooting page

And reword the Expo package text to explicitely point to the Expo team

closes: https://github.com/getsentry/sentry-docs/issues/5696

2022-12-19 15:51 UTC, kahest requested changes
`h`: we also need to adapt [the install section](https://github.com/getsentry/sentry-docs/blob/master/src/platform-includes/getting-started-install/react-native.mdx#expo) - I suggest removing the troubleshooting link but keeping the section

2022-12-19 15:51 UTC, kahest commented on src/platform-includes/getting-started-primer/react-native.mdx
> +- [Expo package](https://docs.expo.io/guides/using-sentry/) supported by the Expo team
```suggestion
- [Expo package](https://docs.expo.io/guides/using-sentry/) maintained by the Expo team
```

2022-12-19 15:52 UTC, kahest commented on src/platform-includes/getting-started-primer/react-native.mdx
> +- [Expo package](https://docs.expo.io/guides/using-sentry/) supported by the Expo team
Otherwise LGTM - thank you 🚀

2022-12-20 09:27 UTC, marandaneto approved these changes
LGTM after adressing @kahest comment.

2023-01-03 16:51 UTC, merged