feat(replays): Document the new search properties available for the Replay DOM Search feature
getsentry/sentry-docs pull request #6465
Opened 2023-03-13 23:00 UTC by ryan953

Fixes #6464

2023-03-14 16:57 UTC, lizokm commented
Hi hi! @ryan953 Would you like me to take a look at this while it's still in draft or should I hold off for now?

2023-04-10 21:19 UTC, cmanallen requested changes

2023-04-11 07:27 UTC, ryan953 commented on src/docs/product/sentry-basics/search/searchable-properties.mdx
> +
is `selector` in-scope now?! woo!

2023-04-11 14:16 UTC, cmanallen commented on src/docs/product/sentry-basics/search/searchable-properties.mdx
> +
@ryan953 Sure is :D

2023-04-12 04:28 UTC, ryan953 commented
@lizokm I think this is ready for your eyes. We've settled on the list of fields, no new fields will be added so we can describe what we have.

One thing that might change is the the prefix `replay_click` might become just `click`... i'm not sure who's going to come down and decide that change or not. so TBD for now.

2023-04-18 16:11 UTC, bruno-garcia approved these changes

2023-04-18 17:08 UTC, lizokm approved these changes
Just a few small tweaks.

2023-04-18 17:08 UTC, lizokm commented on src/docs/product/sentry-basics/search/searchable-properties.mdx
> +| click.title | The `title` of an element that was clicked. For example `Save this comment` would match the element `<a title="Save this comment" class="btn btn-primary">Save</a>` | | | x | string |
```suggestion
| click.alt | The `alt` of an element that was clicked. For example, `"a good dog"` would match the element `<img src="/lassie.jpeg" alt="a good dog" />` | | | x | string |
| click.class | The `class` of an element that was clicked. No leading `.` is necessary. For example, `btn-primary` would match the element `<a class="btn btn-primary">Save</a>` | | | x | string |
| click.id | The `id` of an element that was clicked. No leading `#` is necessary. For example, `reset-password` would match the element `<a id="reset-password">Reset</a>` | | | x | string |
| click.label | The `aria-label` of an element that was clicked. For example, `Expand` would match the element `<button aria-label="Expand"><img src="/icons/expand.png"/></button>` | | | x | string |
| click.role | The `role` of an element that was clicked. For example, `button` would match both `<button>Save</button>` and `<a role="button">Submit</a>` | | | x | string |
| click.selector | An element identified using a subset of CSS selector syntax. For example, `span#section-1` or `span.active` or `span[role=button]` or `span#section-1.active[role=button]` would all match the element `<span id="section-1" class="active" role="button"/>`. Note that, CSS combinators, pseudo selectors, and attr selectors other than `=` are not supported. | | | x | string |
| click.tag | The tag name of an element that was clicked. For example, `input` would match `<input name="username" />` | | | x | string |
| click.textContent | The immediate `textContent` of an element that was clicked. For example, `Save` would match `<button>Save</button>` but wouldn't match `<button><h1>Save</h1></button>` | | | x | string |
| click.title | The `title` of an element that was clicked. For example, `Save this comment` would match the element `<a title="Save this comment" class="btn btn-primary">Save</a>` | | | x | string |
```

2023-04-18 20:21 UTC, merged