feat(android): logcat integration
getsentry/sentry-docs pull request #6543
Opened 2023-03-27 13:31 UTC by buenaflor

Docs for the logcat integration added through SAGP

2023-03-27 17:45 UTC, shanamatthews approved these changes
minor phrasing tweaks

2023-03-27 17:48 UTC, shanamatthews commented on src/platforms/android/configuration/integrations/logcat.mdx
> +This snippet captures an intentional error, so you can test that everything is working as soon as you set it up:
```suggestion
This snippet captures an intentional error, so you can test that everything is working once you've set it up:
```

2023-03-28 05:36 UTC, markushi requested changes
Nice one, please have a look at my comments. Also: Let's make sure we merge this after the feature is released.

2023-03-28 05:36 UTC, markushi commented on src/platforms/android/configuration/integrations/logcat.mdx
> +The Sentry Logcat integration adds support for automatically attaching breadcrumbs to events above a minimum logging level. Only explicit log calls are captured as breadcrumbs, logs that were created
I think we can phrase this more positive.

```suggestion
The Sentry Logcat integration adds support for automatically reporting log calls above a minimum logging level as breadcrumbs. Any matching `android.Log.*` calls inside your app package are captured as breadcrumbs, including `android.Log.*` calls originating from bundled third party libraries.
```

2023-03-28 05:36 UTC, markushi commented on src/platforms/android/configuration/integrations/logcat.mdx
> +## Auto-Installation With the Sentry Android Gradle Plugin
```suggestion
## Installation With the Sentry Android Gradle Plugin
```

2023-03-28 05:36 UTC, markushi commented on src/platforms/android/configuration/integrations/logcat.mdx
> +Auto-instrumentation is enabled by default, so no further configuration is required. If you'd like to disable the Logcat instrumentation feature, we expose a configuration option for that:
```suggestion
Auto-instrumentation is enabled by default, so no further configuration is required. If you'd like to disable the Logcat instrumentation feature, or change the minimum log level the following options are provided:
```

2023-03-28 05:36 UTC, markushi commented on src/platforms/android/configuration/integrations/logcat.mdx
> +```groovy
```suggestion
```groovy {filename:app/build.gradle}
```

2023-03-28 05:36 UTC, markushi commented on src/platforms/android/configuration/integrations/logcat.mdx
> +```kotlin
```suggestion
```kotlin {filename:app/build.gradle.kts}
```

2023-03-28 05:36 UTC, markushi commented on src/platforms/android/configuration/integrations/logcat.mdx
> +
Could you add a screenshot similar as well here? Here's how I did it for Jetpack Compose: https://github.com/getsentry/sentry-docs/pull/6510/files

2023-03-28 05:36 UTC, markushi commented on src/platforms/android/configuration/integrations/logcat.mdx
> +import timber.log.Timber;
I think that's the wrong import

2023-03-28 05:36 UTC, markushi commented on src/platforms/android/configuration/integrations/logcat.mdx
> +    Log.w("MyTag", "Warning message.")
I think the import is missing for `Log`

2023-04-05 08:50 UTC, markushi approved these changes
Nice one, let's ship this!

2023-04-05 09:34 UTC, merged