Highlighting github enterprise
getsentry/sentry-docs pull request #6674
Opened 2023-04-19 11:22 UTC by rodolfoBee

Changing the highlight for GitHub enterprise steps as it is" hidden" in the steps for Github.

2023-04-19 11:32 UTC, rodolfoBee commented
Might also need to change the "Configure" highlight to match, what do you think?

2023-04-19 14:21 UTC, armenzg approved these changes
Please add a before and after screenshot in the PR for posterity. Thanks.

2023-04-19 17:23 UTC, shanamatthews requested changes

2023-04-19 17:23 UTC, shanamatthews commented on src/docs/product/integrations/source-code-mgmt/github/index.mdx
> +# GitHub Enterprise
```suggestion
## GitHub Enterprise
```

If you make this an L1 heading, it won't show up in the docs sidebar:
<img width="202" alt="Screenshot 2023-04-19 at 10 22 35 AM" src="https://user-images.githubusercontent.com/3520671/233152328-66582406-76a6-494e-b5c0-6343f15a2a85.png">

2023-04-27 18:41 UTC, shanamatthews approved these changes

2023-04-27 18:41 UTC, shanamatthews commented
@rodolfoBee I'm gonna go ahead and give this a courtesy merge.

2023-04-27 18:42 UTC, merged