ref: Remove deprecated client pages
getsentry/sentry-docs pull request #7004
Opened 2023-05-23 14:13 UTC by HazAT

I opened this PR to remove the old deprecated `/client` SDK pages.
It's shitty for our users that they land on these pages when visiting from Google - they don't provide any value anymore because if people have troubles or bugs in their old SDKs we tell them to upgrade.

2023-05-23 14:18 UTC, Lms24 approved these changes

2023-05-23 14:37 UTC, cleptric requested changes
Sorry for pulling a ❌ here.

We still have users using old versions of our SDKs, mainly the Raven ones. These users still want to have access to the docs.

2023-05-23 14:51 UTC, HazAT commented
I am fine with not deleting, but we have to solve this - every time our internal search or a search engine guides a user to these pages, we fail.

They should only be accessible with direct links and contain a warning that this is a legacy SDK.

2023-05-24 08:47 UTC, HazAT commented
Closing in favor of https://github.com/getsentry/sentry-docs/pull/7007

2023-05-24 08:47 UTC, closed without merging