Add Remix wizard instructions
getsentry/sentry-docs pull request #7768
Opened 2023-09-07 15:10 UTC by onurtemizkan

Fixes: #7727
Continues: https://github.com/getsentry/sentry-docs/pull/7728

Can't push commits to the original PR, so opened a new one.

2023-09-07 17:14 UTC, AbhiPrasad commented on src/platform-includes/getting-started-install/javascript.remix.mdx
> +To learn how to connect your app to Sentry and deploy it on Vercel, see the [Vercel integration](/product/integrations/deployment/vercel/).
We can remove this for Remix users.

```suggestion
```

2023-09-07 23:38 UTC, lizokm approved these changes
Made some suggestions, but otherwise this looks great!

2023-09-07 23:38 UTC, lizokm commented on src/platforms/javascript/guides/remix/manual-setup.mdx
> +## Installation
```suggestion
## Installation

Get started by installing the below:
```

2023-09-07 23:38 UTC, lizokm commented on src/platforms/javascript/guides/remix/manual-setup.mdx
> +Create two files in the root directory of your project, `entry.client.tsx` and `entry.server.tsx` (if they don't exist yet). In these files, add your initialization code for the client-side SDK and s
```suggestion
Create two files in the root directory of your project, `entry.client.tsx` and `entry.server.tsx` (if they don't already exist). Add your initialization code in these files for the client-side and server-side SDK, respectively.
```

2023-09-07 23:38 UTC, lizokm commented on src/platforms/javascript/guides/remix/manual-setup.mdx
> +If you use a custom Express server in your Remix application, you should wrap your [`createRequestHandler` function](https://remix.run/docs/en/v1/other-api/adapter#createrequesthandler) manually with
```suggestion
If you use a custom Express server in your Remix application, you should wrap your [`createRequestHandler` function](https://remix.run/docs/en/v1/other-api/adapter#createrequesthandler) manually with `wrapExpressCreateRequestHandler`. This isn't necessary if you're using the built-in Remix App Server.
```

2023-09-07 23:38 UTC, lizokm commented on src/platforms/javascript/guides/remix/manual-setup.mdx
> +## Remix v2 features
```suggestion
## Remix v2 Features
```

2023-09-07 23:38 UTC, lizokm commented on src/platforms/javascript/guides/remix/manual-setup.mdx
> +To capture errors from [v2 ErrorBoundary](https://remix.run/docs/en/main/route/error-boundary-v2), you should define your own `ErrorBoundary` in `root.tsx` and use `Sentry.captureRemixErrorBoundaryEr
```suggestion
To capture errors from [v2 ErrorBoundary](https://remix.run/docs/en/main/route/error-boundary-v2), you should define your own `ErrorBoundary` in `root.tsx` and use `Sentry.captureRemixErrorBoundaryError` inside of it. You can also create route-specific error capturing behavior by defining `ErrorBoundary` in your route components. The `ErrorBoundary` you define in `root.tsx` will be used as a fallback for all routes.
```

2023-09-07 23:38 UTC, lizokm commented on src/platforms/javascript/guides/remix/manual-setup.mdx
> +When using `v2_errorBoundary` future flag, Sentry can't capture your server-side errors automatically. Instead, define a [`handleError`](https://remix.run/docs/en/main/file-conventions/entry.server#h
```suggestion
Sentry won't be able to capture your server-side errors automatically if you're using the`v2_errorBoundary` future flag. To work around this, define a [`handleError`](https://remix.run/docs/en/main/file-conventions/entry.server#handleerror) function in your server entry point. Then use `Sentry.captureRemixServerError` to capture errors in your server-side code.
```

2023-09-07 23:38 UTC, lizokm commented on src/platforms/javascript/guides/remix/manual-setup.mdx
> +Once you've done this set up, the SDK will automatically capture unhandled errors and promise rejections, and monitor performance in the client. You can also [manually capture errors](/platforms/java
```suggestion
After you've completed this setup, the SDK will automatically capture unhandled errors and promise rejections, and monitor performance in the client. You can also [manually capture errors](/platforms/javascript/guides/remix/usage).
```

2023-09-07 23:38 UTC, lizokm commented on src/platforms/javascript/guides/remix/manual-setup.mdx
> +You can refer to [Remix Docs](https://remix.run/docs/en/v1/guides/envvars#browser-environment-variables) to learn how to use your Sentry DSN from environment variables.
```suggestion
You can refer to [Remix Docs](https://remix.run/docs/en/v1/guides/envvars#browser-environment-variables) to learn how to use your Sentry DSN with environment variables.
```

2023-09-08 07:14 UTC, Lms24 approved these changes
LGTM once the suggestions are applied, thanks Onur!

2023-09-08 07:14 UTC, Lms24 commented on src/platforms/javascript/guides/remix/manual-setup.mdx
> +## Custom Express Server
l: I'd prefer this section and the v2 support section to switch places unless there's a concrete reason to have custom express server instructions come first(?) My thinking is that showing that we support v2 (future flags) is more important than custom servers.

2023-09-08 07:14 UTC, Lms24 commented on src/platforms/javascript/guides/remix/manual-setup.mdx
> +## Installation
l: Would just suggest a slight change here:
```suggestion
## Installation

Get started by installing the Sentry Remix SDK:
```

2023-09-08 09:35 UTC, Lms24 requested changes
Only requesting changes so we don't merge this until https://github.com/getsentry/sentry-wizard/issues/433 is resolved. Let's only publish this once the wizard is fully ready.

2023-09-15 13:49 UTC, Lms24 approved these changes
We released the wizard with the org/project fix yesterday so this is ready to go. Just one small suggestion but otherwise ready to 🚢

2023-09-15 13:49 UTC, Lms24 commented on src/platform-includes/getting-started-install/javascript.remix.mdx
> +- create `.sentryclirc` with an auth token to upload source maps (this file is automatically added to `.gitignore`).
```suggestion
- create `.sentryclirc` with an auth token to upload source maps (this file is automatically added to `.gitignore`).
- adjust your `build` script in `package.json` to automatically upload source maps to Sentry.
```

2023-09-18 17:59 UTC, shanamatthews approved these changes

2023-09-18 17:59 UTC, shanamatthews commented on src/platforms/javascript/guides/remix/manual-setup.mdx
> +Initialize Sentry in your entry point for the server to capture exceptions and get performance metrics for your [`action`](https://remix.run/docs/en/v1/api/conventions#action) and [`loader`](https://
Looks like these links have moved

```suggestion
Initialize Sentry in your entry point for the server to capture exceptions and get performance metrics for your [`action`](https://remix.run/docs/en/1.19.3/route/action) and [`loader`](https://remix.run/docs/en/1.19.3/route/loader) functions. You can also initialize Sentry's database integrations, such as <Link to="/platforms/node/performance/database/opt-in/#prisma-orm-integration">Prisma</Link>, to get spans for your database calls.
```

2023-09-18 18:09 UTC, onurtemizkan commented on src/platforms/javascript/guides/remix/manual-setup.mdx
> +Initialize Sentry in your entry point for the server to capture exceptions and get performance metrics for your [`action`](https://remix.run/docs/en/v1/api/conventions#action) and [`loader`](https://
@shanamatthews - v2.0.0 is published so we can use `main` here instead. 

```suggestion
Initialize Sentry in your entry point for the server to capture exceptions and get performance metrics for your [`action`](https://remix.run/docs/en/main/route/action) and [`loader`](https://remix.run/docs/en/main/route/loader) functions. You can also initialize Sentry's database integrations, such as <Link to="/platforms/node/performance/database/opt-in/#prisma-orm-integration">Prisma</Link>, to get spans for your database calls.
```

2023-09-19 13:51 UTC, merged