Pre SDK power update (Java)
getsentry/sentry-docs pull request #8202
Opened 2023-10-13 12:51 UTC by stephanie-anderson

- moved integrations from `/configuration/integrations` to `/integrations` as preparation for the SDK power update
  - added redirects

2023-10-13 14:50 UTC, adinauer requested changes
Links seem broken in preview.

2023-10-13 14:50 UTC, adinauer commented on src/platform-includes/crons/setup/java.mdx
> +If you are using [Quartz](http://www.quartz-scheduler.org/), please see <PlatformLink to="/configuration/quartz/">our Quartz integration</PlatformLink>. If you are using Spring Boot with `@Scheduled`
```suggestion
If you are using [Quartz](http://www.quartz-scheduler.org/), please see <PlatformLink to="/integrations/quartz/">our Quartz integration</PlatformLink>. If you are using Spring Boot with `@Scheduled` tasks, see [our Spring Boot integration](/platforms/java/guides/spring-boot/crons/).
```

2023-10-13 14:50 UTC, adinauer commented on src/platform-includes/crons/setup/java.spring-boot.mdx
> +If you are using [Quartz](http://www.quartz-scheduler.org/), please see <PlatformLink to="/integrations/quartz/">our Quartz integration</PlatformLink>. You may also [send check-ins manually](/platfor
Link 404s because "Integrations" is missing for Spring Boot, maybe others as well.

2023-10-18 05:54 UTC, adinauer approved these changes
Mostly LGTM, there's a bad link (see failing build) and I'm not sure the apple entries in `vercel.json` were intended.

2023-10-19 16:53 UTC, stephanie-anderson commented
@adinauer Thank you for all your feedback! Checked the redirects and moved the last image into its subfolder

2023-10-19 16:53 UTC, merged