Pre SDK power update (enriching events)
getsentry/sentry-docs pull request #8211
Opened 2023-10-13 15:20 UTC by stephanie-anderson

- moved everything under `/enriching-events/` into separate subfolders for better readabilty, e.g.
  - `src/platforms/common/enriching-events/context.mdx` to
  - `src/platforms/common/enriching-events/context/index.mdx` and grouped it with its images
- renamed `/enriching-events/identify-user` to `/enriching-events/user`

2023-10-16 23:04 UTC, shanamatthews requested changes
It seems that your new redirects aren't working correctly. For example this path "/platforms/go/enriching-events/attachments/" doesn't work on this build.

Also, do we need the "Events" page? Is the plan to put more subpages there, or can "Enriching Events" be promoted up a level?

2023-10-17 19:55 UTC, stephanie-anderson commented
> It seems that your new redirects aren't working correctly. For example this path "/platforms/go/enriching-events/attachments/" doesn't work on this build.
> 
> Also, do we need the "Events" page? Is the plan to put more subpages there, or can "Enriching Events" be promoted up a level?

Hey Shana, I will take a look at the redirects as soon as possible - thanks for pointing it out! Regarding the Events, yes the `Enriching Events` will be just one of many items under `Events`:
<img width="268" alt="Screenshot 2023-10-17 at 12 53 58" src="https://github.com/getsentry/sentry-docs/assets/7096858/b58c3cc1-c8ec-4728-b939-41723aac57fe">

Moving `Enriching Events` is such a huge change, that I didn't want to mingle it with other changes

2023-10-18 09:21 UTC, mydea commented
I wonder if `Events` should not be a top-level options (next to Usage, not under it) - feels like a lot of steps right now, and honestly I did not go looking for this inside of Usage 😅 IMHO if we have a bunch of items under this, it's warranted to have this on top, as it's also something people are likely to go looking for...?

2023-10-19 20:55 UTC, stephanie-anderson commented
> I wonder if `Events` should not be a top-level options (next to Usage, not under it) - feels like a lot of steps right now, and honestly I did not go looking for this inside of Usage 😅 IMHO if we have a bunch of items under this, it's warranted to have this on top, as it's also something people are likely to go looking for...?

@mydea I get that the content is really important, but is it not about the `usage` of events and what one can do with them? If we imagine we'd point users to `enriching events` whenever it makes sense, would you still be against moving it to the usage context? I guess the need for putting it in the first level of navigation is because you think users will otherwise not find the content? I'd really really like to get a consensus on that change before it goes out. Happy to also talk next week so it does not need to be async

2023-10-20 22:44 UTC, shanamatthews requested changes
Just a few small issues left that I found!!

2023-10-20 22:44 UTC, shanamatthews commented on vercel.json
I can't see from a glance why /enriching-events/identify-user/ doesn't work here :/

2023-10-20 22:44 UTC, shanamatthews commented on src/platforms/common/usage/sdk-fingerprinting.mdx
> +  - ../../../usage/events/enriching-events/context/fingerprint-override/
I think this change was a mistake, although it looks like even the existing redirect here doesn't work

```suggestion
  - ../../../enriching-events/context/fingerprint-override/
```

2023-12-13 21:31 UTC, closed without merging