feat(open-pr-comments): docs
getsentry/sentry-docs pull request #8883
Opened 2024-01-16 20:18 UTC by cathteng

2024-01-16 21:44 UTC, cathteng commented on src/docs/product/integrations/source-code-mgmt/github/index.mdx
>  ### Get Sentry Comments on Suspect Pull Requests
```suggestion
### Get Sentry Comments on Pull Requests
```

2024-01-16 22:01 UTC, vivianyentran requested changes
Looks good! Added some suggestions. Can you also add an EA note for the EA features (not sure if it's all 3 features or just 1 of them)?

2024-01-16 22:02 UTC, cathteng commented on src/docs/product/integrations/source-code-mgmt/github/index.mdx
> +These features will be automatically enabled for you once your GitHub integration has been set up. To disable it, go to **Settings > Integrations > GitHub** and toggle it off.
hmm how about "Sentry can comment on merged and open pull requests" since they do different things?

2024-01-16 22:02 UTC, cathteng commented on src/docs/product/integrations/source-code-mgmt/github/index.mdx
> +When a pull request is opened, Sentry will parse the filenames and function names modified in the pull request from the PR diff to find recent unhandled, unresolved issues associated with your pull r
it's only errors for now... but i can modify this

2024-01-16 22:03 UTC, cathteng commented on src/docs/product/integrations/source-code-mgmt/github/index.mdx
> +These features will be automatically enabled for you once your GitHub integration has been set up. To disable it, go to **Settings > Integrations > GitHub** and toggle it off.
where would you suggest putting this?

2024-01-16 23:18 UTC, vivianyentran commented on src/docs/product/integrations/source-code-mgmt/github/index.mdx
> +When a pull request is opened, Sentry will parse the filenames and function names modified in the pull request from the PR diff to find recent unhandled, unresolved issues associated with your pull r
Oh, it should be modified in the UI also then!

2024-01-16 23:18 UTC, vivianyentran commented on src/docs/product/integrations/source-code-mgmt/github/index.mdx
> +These features will be automatically enabled for you once your GitHub integration has been set up. To disable it, go to **Settings > Integrations > GitHub** and toggle it off.
that's perfect!

2024-01-16 23:19 UTC, cathteng commented on src/docs/product/integrations/source-code-mgmt/github/index.mdx
> +When a pull request is opened, Sentry will parse the filenames and function names modified in the pull request from the PR diff to find recent unhandled, unresolved issues associated with your pull r
true, thanks!

2024-01-16 23:19 UTC, vivianyentran commented on src/docs/product/integrations/source-code-mgmt/github/index.mdx
> +These features will be automatically enabled for you once your GitHub integration has been set up. To disable it, go to **Settings > Integrations > GitHub** and toggle it off.
Oh, this was an old comment. I think the updated header clarifies this now so I'll go ahead and resolve this

2024-01-16 23:27 UTC, vivianyentran commented
Can you also make sure to add a bullet for these EA features to the bottom of this page: https://docs.sentry.io/product/accounts/early-adopter-features/

2024-01-17 00:29 UTC, vivianyentran approved these changes
Looks good! Just a reminder to remove performance issues from the UI text and update that image here when ready!

2024-01-17 00:29 UTC, vivianyentran commented on src/docs/product/integrations/source-code-mgmt/github/index.mdx
> +When a pull request is opened, Sentry will parse the filenames and function names modified in the pull request from the PR diff to find recent unhandled, unresolved issues associated with your pull r
```suggestion
When a pull request is opened, Sentry will parse the filenames and function names modified to find recent error issues associated with the code changes.
```
Looks like this got missed?

2024-01-17 00:29 UTC, cathteng commented on src/docs/product/integrations/source-code-mgmt/github/index.mdx
> +When a pull request is opened, Sentry will parse the filenames and function names modified in the pull request from the PR diff to find recent unhandled, unresolved issues associated with your pull r
oh oops, thanks!

2024-01-17 17:36 UTC, merged