Fix beforeSend signature in code snippets for dart platforms
getsentry/sentry-docs pull request #9770
Opened 2024-04-22 13:02 UTC by romatallinn

Adjust documentation to reflect a breaking change to a `beforeSend` signature introduced in v8.0.0: https://github.com/getsentry/sentry-dart/issues/1478 

## Pre-merge checklist

*If you work at Sentry, you're able to merge your own PR without review, but please don't unless there's a good reason.*

- [ ] Checked Vercel preview for correctness, including links
- [ ] PR was reviewed and approved by any necessary SMEs
- [ ] PR was reviewed and approved by a member of the [Sentry docs team](https://github.com/orgs/getsentry/teams/docs)

## Legal Boilerplate

Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. and is gonna need some rights from me in order to utilize my contributions in this here PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, under Sentry's choice of terms.

2024-04-22 16:56 UTC, vivianyentran commented
@buenaflor can you please review?

2024-04-23 11:29 UTC, buenaflor requested changes
Small correction on `beforeBreadcrumb`

Thanks for the pr!

2024-04-23 11:29 UTC, buenaflor commented on platform-includes/configuration/before-breadcrumb-hint/dart.mdx
> +Breadcrumb beforeBreadcrumb(Breadcrumb crumb, Hint hint) {
```suggestion
Breadcrumb? beforeBreadcrumb(Breadcrumb? breadcrumb, Hint hint) {
```

2024-04-23 11:29 UTC, buenaflor commented on platform-includes/enriching-events/breadcrumbs/before-breadcrumb/dart.mdx
> +Breadcrumb beforeBreadcrumb(Breadcrumb breadcrumb, Hint hint) {
```suggestion
Breadcrumb? beforeBreadcrumb(Breadcrumb? crumb, Hint hint) {
```

2024-04-23 12:24 UTC, romatallinn commented
@buenaflor good to go

2024-04-23 12:28 UTC, buenaflor approved these changes

2024-04-23 16:16 UTC, vivianyentran approved these changes

2024-04-23 16:31 UTC, merged